@startuml
class Eatery {
- Long id
- Type type
- String name
- String address
- String email
- String phoneNumber
- int guestCapacity
- Set<AppUser> favouriteUsers
- List<Reservation> reservationList
- Set<BusinessDayTime> businessDayTimes
+ boolean isOpen()
+ boolean isFullyBooked(LocalDateTime,int)
+ boolean equals(Object)
+ int hashCode()
+ String toString()
}
@enduml