@startuml
class Reservation {
- Long id
- AppUser user
- Eatery eatery
- LocalDateTime reservationDateTime
- int personNumber
- Status status
+ boolean equals(Object)
+ int hashCode()
+ String toString()
}
@enduml