@startuml
class AppUser {
- Long id
- String firstName
- String lastName
- String email
- String phoneNumber
- List<Eatery> favouriteEateries
- List<Reservation> reservations
+ boolean equals(Object)
+ int hashCode()
+ String toString()
}
@enduml