@startuml
class Customer {
- Long id
- String firstName
- String lastName
- String email
- String phoneNumber
- List<Reservation> reservations
- PaymentMethod paymentMethod
- List<Review> reviews
+ boolean equals(Object)
+ int hashCode()
+ String toString()
}
@enduml