@startuml
class EateryManager {
- Long id
- String firstName
- String lastName
- String email
- String phoneNumber
- Long eateryId
- String jobTitle
- Set<WorkSchedule> workSchedules
+ boolean equals(Object)
+ int hashCode()
+ String toString()
}
@enduml