@startuml
class Reservation {
- Long id
- Long customerId
- Long eateryId
- LocalDateTime reservationDateTime
- int guestNumber
- ReservationStatus status
+ boolean equals(Object)
+ int hashCode()
+ String toString()
}
@enduml