@startuml
class Reservation {
- Long id
- Customer customer
- Eatery eatery
- LocalDateTime reservationDateTime
- int guestNumber
- Status status
+ boolean equals(Object)
+ int hashCode()
+ String toString()
}
@enduml