@startuml
class WorkSchedule {
- DayOfWeek workDay
- LocalTime startTime
- LocalTime endTime
+ boolean equals(Object)
+ String toString()
+ LocalTime endTime()
+ DayOfWeek workDay()
+ LocalTime startTime()
}
@enduml